api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    collection:
        pagination:
            enabled: false

services:
    offer.search_filter:
        parent:  'api_platform.doctrine.orm.search_filter'
        arguments: [ { domainDns: 'exact' } ]
        tags: [ 'api_platform.filter' ]